### ISSUE TITLE
Validator blows up with message `thing.parameters.map is not a function` when "allOf" appears as the first child of a parameters block

### ISSUE THREAD

**Issue by tbenda-SEL** [IBM/openapi-validator#101]
Using `lint-openapi` version `0.13.3`

When an `allOf` appears (apparently illegally) as the first child of a `parameters` block on a path operation, rather than failing with a useful error message, it exits with:

> [Error] There was a problem with a validator.
> thing.parameters.map is not a function

A yaml file that (minimally?) reproduces the issue is here:

herp.yaml
```yaml
---
openapi: 3.0.0
info:
  version: 0.0.1
  title: herp
  contact:
    name: yeah
    email: nobody@example.com

paths:
  /derp:
    get:
      parameters:
        allOf:
          - name: grog
            type: string
          - name: fnord
            type: string
      description: herp
      responses:
        "200":
          description: response
```

It would be preferable that it would fail with a message reflecting that the usage was unexpected or illegal.

**Comment by dpopp07** [comment]
@tbenda-SEL Also agreed, the validator should be able to continue processing this.

FYI, this is illegal because `allOf` is a property of JSON Schema and is only allowed in an OpenAPI definition when describing a schema. The `parameters` object in an operation must be an array of parameter objects or $refs. You may have known that, just wanted to be complete 🙂 

Thanks for posting
