### ISSUE TITLE
Config unused_tag is confusing

### ISSUE THREAD

**Issue by jormaechea** [IBM/openapi-validator#170]
Shouldn't be it `undefined_tag`? Because that's what that config checks:
> Flag a tag that is in operations and not listed in tags on the top level.

IMO, `unused_tag` could be a new rule that performs the following check:
> Flag a tag that is listed in tags on the top level, but not used by any operation.

What do you think? I know it's a breaking change, but you're still in v0.x.x..

**Comment by dpopp07** [comment]
@jormaechea thanks for opening the issue. I think you're right about that and since we're still technically in "pre-release" I'm not opposed to making a breaking change.

Is this something you could open a PR for? I'm having trouble prioritizing this tool at the moment but I would be happy to review a PR.

**Comment by jormaechea** [comment]
Sure, I’ll let you know when it's ready!

**Comment by jormaechea** [comment]
@dpopp07 we should close this, right?

**Comment by dpopp07** [comment]
Yep, thought I already had. Thanks for the reminder!
