### ISSUE TITLE
What is the purpose of requiring `x-codegen-request-body-name`?

### ISSUE THREAD

**Issue by cwgormanIBM** [IBM/openapi-validator#183]
This is one of the default rules, but I'm not sure what it is or does. From Googling, it looks like a holdover from a swagger generator tool?

**Comment by dpopp07** [comment]
This is actually a custom rule specific to our set of tools. One of the primary way this validator is used is to prepare API Definitions for SDK generation (using our internal SDK generator). We require the use of `x-codegen-request-body-name` because it results in drastically better generated SDKs.

This rule should be configurable, you should be able to turn it off if need be. Are you seeing that isn't the case?
