### ISSUE TITLE
Why All responses must include a description cannot be disabled?

### ISSUE THREAD

**Issue by Havunen** [IBM/openapi-validator#203]
Hey,

Why validation rule for All responses must include a description cannot be disabled? 
I cant find this being required in the Open APi 3 specification?

Code: https://github.com/IBM/openapi-validator/blob/4277079d2651ef8324dc76fb226033f19273aab6/src/plugins/validation/oas3/semantic-validators/responses.js#L54-L60

empty `""` -description gives error

**Comment by dpopp07** [comment]
Hi @Havunen, this rule is non-configurable because descriptions are required for Response Objects [in the OpenAPI 3 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responseObject).

This is the relevant snippet:

description | string | REQUIRED. A short description of the response. CommonMark syntax MAY be used for rich text representation.
-- | -- | --

**Comment by Havunen** [comment]
Okay, thanks for the reply. 

I found a way to filter out these errors for now, but yeah it makes sense If its required in the spec, thanks
