### ISSUE TITLE
Validator allows duplicate `operationId` values in some cases

### ISSUE THREAD

**Issue by danhudlow** [IBM/openapi-validator#28]
At least when two operations use a `$ref` to the same operation object, the validator doesn't seem to pick up on the consequentially shared `operationId`.

**Comment by dpopp07** [comment]
It does look for duplicated operation ids, but that's an interesting edge case that I guess it can't handle. That's worth looking into, thanks for the issue

**Comment by dpopp07** [comment]
Hey @danhudlow, finally getting around to looking at this. I'm wondering about this pattern that you're finding the problem with. It doesn't look like the spec supports referencing entire operations (based on [the definition of a path object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#path-item-object)).

Are you storing operation objects under `schemas` (or `definitions` if using OpenAPI 2) and then referencing them at the path level like so? :

```json
"/some/path": {
  "get": {
    "$ref": "#/components/schemas/Operation1"
  }
}
```

I guess I'm also a little confused why you would create a named schema for an operation since they shouldn't be used more than once.

**Comment by dhudlow** [comment]
The path item object itself can contain a reference, and I have seen two different paths offer the same behavior by referencing the same path item object.

**Comment by dpopp07** [comment]
Ah yes, you're correct. Thanks for setting me straight. That still seems like an odd pattern to me, since any path item shared between two paths would have the colliding operation ID problem you originally mentioned (if the shared path item has an operation defined). That said, I understand the use case so I'll add logic just to check the existence of duplicated IDs.

**Comment by dpopp07** [comment]
@dhudlow Have a look at the test case in #31 and let me know if that is a realistic and/or appropriate use case for what you were looking to fix.

**Comment by dhudlow** [comment]
Looks right to me!
