### ISSUE TITLE
Any support for browser?

### ISSUE THREAD

**Issue by chrisdudley** [IBM/openapi-validator#289]
Are there any plans to allow this to be run from a browser?
Currently a lot of the dependencies do a lot of fs operations to get config which obviously don't work in a browser.

We'd like to be able to validate OAI documents in a web app.

**Comment by dpopp07** [comment]
@chrisdudley There are no plans for that right now. This project was actually originally converted from a browser app (years ago) because there was little interest in using the browser for validation and lots of interest in a CLI tool.

That said, this tool is also available as an NPM package and can be executed within a server-side Node app. You could create a web app that runs validation on the server and returns the results to the browser.

**Comment by dpopp07** [comment]
All of our rules are now available as an independent NPM package, formatted as a Spectral ruleset. If the node module version of the validator does not work in the browser, [Spectral itself should](https://meta.stoplight.io/docs/spectral/eb68e7afd463e-spectral-in-java-script#browser) and it's possible to run only the full suite of rules from this package.
